45
***********
*28*lake1.jpg*4*Lake View*<p>Cherry Lake, Sumter County Commercail Property is located close to the villages and has a wonderful growth rate. This property would be great for any type of commercial development or as an investment property.</p><br /><a href='./live-bdg/files/WhiteHypes.pdf'>PDFabout the property</a><br /><a href='./live-bdg/files/WhiteHypes.ppt'>Powerpoint presentation</a>. *534750*750*575*150*112*1136345506
*29*sign3.jpg*4*Signage 3*<br /><p>Cherry Lake, Sumter County Commercail Property is located close to the villages and has a wonderful growth rate. This property would be great for any type of commercial development or as an investment property.</p><br /><a href='./live-bdg/files/WhiteHypes.pdf'>PDFabout the property</a><br /><a href='./live-bdg/files/WhiteHypes.ppt'>Powerpoint presentation</a>. *1162506*750*575*150*112*1136345612
*30*sign1.jpg*4*Corner of Hwy 466 and CR 100*<br /><p>Cherry Lake, Sumter County Commercail Property is located close to the villages and has a wonderful growth rate. This property would be great for any type of commercial development or as an investment property.</p><a href='./live-bdg/files/WhiteHypes.pdf'>PDFabout the property</a> <a href='./live-bdg/files/WhiteHypes.ppt'>Powerpoint presentation</a>. *956950*750*575*150*112*1136345612
*31*sign2.jpg*4*Signage*<br /><p>Cherry Lake, Sumter County Commercail Property is located close to the villages and has a wonderful growth rate. This property would be great for any type of commercial development or as an investment property.</p><br /><a href='./live-bdg/files/WhiteHypes.pdf'>PDFabout the property</a><br /><a href='./live-bdg/files/WhiteHypes.ppt'>Powerpoint presentation</a>. *1137129*750*575*150*112*1136345612
*32*field3.jpg*4*Field View 3*<p>Cherry Lake, Sumter County Commercail Property is located close to the villages and has a wonderful growth rate. This property would be great for any type of commercial development or as an investment property.</p><br /><a href='./live-bdg/files/WhiteHypes.pdf'>PDFabout the property</a><br /><a href='./live-bdg/files/WhiteHypes.ppt'>Powerpoint presentation</a>. *759669*750*575*150*112*1136345612
*33*field2.jpg*4*Field 2*<p>Cherry Lake, Sumter County Commercail Property is located close to the villages and has a wonderful growth rate. This property would be great for any type of commercial development or as an investment property.</p><br /><a href='./live-bdg/files/WhiteHypes.pdf'>PDFabout the property</a><br /><a href='./live-bdg/files/WhiteHypes.ppt'>Powerpoint presentation</a>. *954489*750*575*150*112*1136345709
*34*Roadside.jpg*4*Roadside view*<p>Cherry Lake, Sumter County Commercail Property is located close to the villages and has a wonderful growth rate. This property would be great for any type of commercial development or as an investment property.</p><br /><p><a href='./live-bdg/files/WhiteHypes.pdf'>PDFabout the property</a></p><br /><a href='./live-bdg/files/WhiteHypes.ppt'>Powerpoint presentation</a>. *679913*750*575*150*112*1136345709
*35*field1.jpg*4*Field View 1*<p>Cherry Lake, Sumter County Commercail Property is located close to the villages and has a wonderful growth rate. This property would be great for any type of commercial development or as an investment property.</p><br /><a href='./live-bdg/files/WhiteHypes.pdf'>PDFabout the property</a><br /><a href='./live-bdg/files/WhiteHypes.ppt'>Powerpoint presentation</a>. *1030679*750*575*150*112*1136345709
*36*roadside2.jpg*4*Road View*<p>Cherry Lake, Sumter County Commercail Property is located close to the villages and has a wonderful growth rate. This property would be great for any type of commercial development or as an investment property.</p><br /><a href='./live-bdg/files/WhiteHypes.pdf'>PDFabout the property</a><br /><a href='./live-bdg/files/WhiteHypes.ppt'>Powerpoint presentation</a>. *582298*750*575*150*112*1136345709
*37*intersection.jpg*4*Intersection of HWY466 and CR100*<p>Cherry Lake, Sumter County Commercail Property is located close to the villages and has a wonderful growth rate. This property would be great for any type of commercial development or as an investment property.</p><br /><a href='./live-bdg/files/WhiteHypes.pdf'>PDFabout the property</a><br /><a href='./live-bdg/files/WhiteHypes.ppt'>Powerpoint presentation</a>. *629431*750*575*150*112*1136345709
