12
*1***5*1***for_sale_sign_thumb.JPG*150*117*<br /><div style=&quot;text-align: center;&quot;>&nbsp;</div>
*2*1*Sale*10*1**1135738896*sign3_thumb.jpg*150*112*<p><font size=&quot;3&quot;>These properties are currently on the market and are going fast. Stop in and check out what we have to offer.</font><br /></p><br /> *
*4*2*Cherry Lake- Sumter County Commercial Property*10*1**1136324353*sign1_thumb.jpg*150*112*<br /><p style=&quot;text-align: center;&quot;>This property is located on Cherry Lake right next to The Villages Lake Sumter Landing. It is ready for development and is set in a key location to the surronding growing area.</p><p style=&quot;text-align: center;&quot;><a href=&quot;../../../files/WhiteHypes.pdf>PDF About the Property</a></p><p style=&quot;></a><a href=&quot;../../../files/WhiteHypes.ppt&quot;>Basic Power Point Presentation on the property</a></p>*
*7*2*Peninsula Property-  Tavares*10*1**1136756029****<table style=&quot;WIDTH: 65%&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; align=&quot;left&quot; border=&quot;0&quot;><tbody><tr><td><p align=&quot;center&quot;>PROPERTY FACT SHEET</p><p align=&quot;left&quot;><u>Acreage:</u> 425 total acres. Approximately 338 acres upland and 87 acres wetland.</p><p align=&quot;left&quot;><u>Government Jurisdiction:</u> City of Tavares, Florida </p><p align=&quot;left&quot;><u>Zoning:</u> Planned Unit Development &mdash; P.U.D.</p><p align=&quot;left&quot;><u>Utilities:</u> City of Tavares: 12&quot; water main and 12&quot; sewer main at Southeast corner of property.</p><p align=&quot;left&quot;><u>Approvals:</u> </p><ul><li><p align=&quot;left&quot;>500 total building lots less existing 17 homesites = 483 total homesites. </p></li><li><p align=&quot;left&quot;>18 hole championship golf course. Road impact fees have been paid for the golf course. </p></li><li><p align=&quot;left&quot;>Marina for residents could be permitted with the State of Florida. The land under the marina would not have to pay an annual lease fee since it wad exempted by a law passed in the 1930&acute;s.</p></li></ul><p align=&quot;left&quot;><u>Additional Facts:</u> </p><ul><li><p align=&quot;left&quot;>City of Tavares is interested in effluent disposal of future golf course.</p></li><li><p align=&quot;left&quot;>Approximately &frac34; mile or 2,600 linear feet of useable lakefront on Big Lake Harris. Lots at 145&acute; wide = 18 lakefront lots.</p></li><li><p align=&quot;left&quot;>80&acute; elevation drop from the highest point on the property to the lakefront. Panoramic views.</p></li><li><p align=&quot;left&quot;>Presently, there exists a 17 lot upscale lakefront subdivision on the West side consisting of approximately 20 acres. Easement access is provided through the 425 acre property. The existing Homeowners Association for the 17 lots must join a Master Association when formed.</p></li></ul></td></tr></tbody></table>
*
*9*1*Lease*5*1**1136766453*sign2_thumb.jpg*150*112*<br /><div style=&quot;text-align: center;&quot;>&nbsp;</div>*
*10*9*2200 Building*10*1**1136766474****<div style=&quot;text-align: center;&quot;>No Current Information<br /></div><div style=&quot;text-align: center;&quot;>&nbsp;</div>*
*11*9*Fish Camp*10*1**1136766497****<div style=&quot;text-align: center;&quot;>No Current Information<br /></div><div style=&quot;text-align: center;&quot;>&nbsp;</div>*
